include:
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "PSE"
    file : base.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "PSE"
    file : image.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "PSE"
    file : chart.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "PSE"
    file : deploy.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "PSE"
    file : website.yaml

# using a parallel DAG pipeline (https://docs.gitlab.com/ee/ci/directed_acyclic_graph/) would be significantly (~ 30 %) faster but is not possible
# at the moment because of limited CI/CD resources

prettier:
  stage: prepare
  image: node:19
  extends: .npmcache
  script:
    - npm run prettier:check
