include:
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "PSE"
    file : base.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "PSE"
    file : image.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "PSE"
    file : chart.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "PSE"
    file : deploy.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "PSE"
    file : website.yaml

style:
  needs: []

npmtest:
  needs: ["npminstall"]

prettier:
  stage: test
  image: node:19
  needs: ["npminstall"]
  extends: .npmcache
  script:
    - npm run prettier:check

npmbuild:
  needs: ["npminstall"]

image-build:
  needs: ["npmbuild"]

chart:
  needs:
    - job: image-build
      artifacts: true
    - job: npmtest
      artifacts: false
    - job: prettier
      artifacts: false
    - job: style

deploy:
  needs: ["chart"]

deploy-main:
  needs: ["chart"]

undeploy:
  needs:
    - job: deploy
      optional: true
    - job: deploy-main
      optional: true

Logging:
  needs: ["undeploy"]

